consecutive_number: 3
devices_status:
- excellent
- good
- warning
- faulty
- killed
- unknown
list_divices:
- satelite
- spacecraft
- space_vehicle
- spacesuit
- other_componentsdata_mission_devices
list_misions:
- OrbitOne
- ColonyMoon
- VacMars
- GalaxyTwo
- Unknow
mission_label:
  ColonyMoon: CLNM
  GalaxyTwo: GALXONE
  OrbitOne: ORBONE
  Unknow: UNKN
  VacMars: TMRS
