consecutive_number: 31
devices_status:
- excellent
- good
- warning
- faulty
- killed
- unknown
labels:
- ORBONE
- CLNM
- TMRS
- GALXONE
- UNKN
list_divices:
- satelite
- spacecraft
- space_vehicle
- spacesuit
- other_componentsdata_mission_devices
list_misions:
- OrbitOne
- ColonyMoon
- VacMars
- GalaxyTwo
- Unknow
